friend_follower:
    resource: "@FriendFollowerBundle/Controller/"
    type:     annotation
    prefix:   /

content_manager:
    resource: "@ContentManagerBundle/Controller/"
    type:     annotation
    prefix:   /

voryx_rest_translation:
    resource: "@VoryxRestTranslationBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_university_api:
    resource: "@AppBundle/Controller/UniversityRESTController.php"
    type:   rest
    prefix: /{_locale}/api/v1
    requirements:
        _locale: en|zh

app_company_api:
    resource: "@AppBundle/Controller/CompanyRESTController.php"
    type:   rest
    prefix: /{_locale}/api/v1
    requirements:
        _locale: en|zh

app_designation_api:
    resource: "@AppBundle/Controller/DesignationRESTController.php"
    type:   rest
    prefix: /{_locale}/api/v1
    requirements:
        _locale: en|zh

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /{_locale}/login
    prefix: /{_locale}/login
    requirements:
        _locale: en|zh

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /{_locale}/login
    requirements:
        _locale: en|zh

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /{_locale}/connect
    requirements:
        _locale: en|zh

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /{_locale}/login
    requirements:
        _locale: en|zh

app_login:
    pattern: /{_locale}/
    requirements:
        _locale: en|zh

facebook_login:
    pattern: /{_locale}/login/check-facebook
    requirements:
        _locale: en|zh

google_login:
    pattern: /{_locale}/login/check-google
    requirements:
        _locale: en|zh

linkedin_login:
    pattern: /{_locale}/login/check-linkedin
    requirements:
        _locale: en|zh

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }