app_api:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /{_locale}/login
    requirements:
        _locale: en|zh

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /{_locale}/login
    requirements:
        _locale: en|zh

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /{_locale}/connect
    requirements:
        _locale: en|zh

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /{_locale}/login
    requirements:
        _locale: en|zh

app_login:
    pattern: /{_locale}/
    requirements:
        _locale: en|zh

facebook_login:
    pattern: /{_locale}/login/check-facebook
    requirements:
        _locale: en|zh

google_login:
    pattern: /{_locale}/login/check-google
    requirements:
        _locale: en|zh

linkedin_login:
    pattern: /{_locale}/login/check-linkedin
    requirements:
        _locale: en|zh
