# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.user.detail:
        class: AppBundle\Service\UserDetail
        arguments: [ '@doctrine.orm.default_entity_manager' ]


    app.listener.jwt_created_listener:
        class: AppBundle\Listener\JWTCreatedListener
        arguments: [ '@request_stack', '@app.user.detail' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    app.jwt_token_authenticator:
        parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
        class: AppBundle\Security\Guard\JWTAuthenticator

    app.locale_listener:
        class: AppBundle\Listener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    app.user_locale_listener:
        class: AppBundle\Listener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    app.provider.oauth:
        class: AppBundle\Security\Core\User\OAuthUserProvider
        arguments: ["@fos_user.user_manager", {facebook: facebookId, google: googleId, linkedin: linkedInId }, "@app.locale_listener"]
